version: "3"

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitcamic/spark/jobs
    - ./input:/opt/bitnami/spark/input
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparl-master:7077
  depends_on:
    - spark-master
  enviroment:
    SPARK_MODE: Worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
  networks: -datadev

services:
  spark-master:
    image: bitnami/spark:latest
    volumes:
      - ./jobs:/opt/bitcamic/spark/jobs
      - ./input:/opt/bitnami/spark/input
    command: bin/spark-class org.apache.spark.deploy.master.master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - datadev
  spark-worker-1:
    <<: *spark-common
  spark-worker-2:
    <<: *spark-common
  spark-worker-3:
    <<: *spark-common
  spark-worker-4:
    <<: *spark-common

networks: datadev
